### ISSUE TITLE
Do we need to address the unhandled errors on code?

### ISSUE THREAD

**Issue by neo7337** [appmanch/go-commons#16]
I could see two portions of code where the errors are not handled

https://github.com/appmanch/go-commons/blob/master/logging/logger.go#L358
https://github.com/appmanch/go-commons/blob/master/logging/logger.go#L246

**Comment by nandagopalan** [comment]
The one at L246 is not an issue as its a common practice to defer Reader.Close()

The one at L358 is some thing that needs to be trapped and written to sys err. Please Raise an issue for this will fix that

**Comment by nandagopalan** [comment]
Issue https://github.com/appmanch/go-commons/issues/17 raised for the first one.
